
// Analyze the problem definition and develop a complete Java.program. 
// A company manufactures different types of electronic devices such as smartphones, laptops, and tablets. Each electronic device has a unique model number, brand name, and price. Additionally, smartphones have unique features like screen size, camera quality, and battery life, while laptops have unique features like screen size, RAM, and hard disk capacity. Tablets also have unique features like screen size, battery life, and storage capacity.
// The company wants to design a software system to keep track of their inventory and sales. The software system should have the following functionalities:
// 1.	Add a new electronic device to the inventory
// 2.	Remove an electronic device from the inventory
// 3.	Search for an electronic device by model number or brand name
// 4.	Display the inventory list with all the details of each electronic device
// 5.	Calculate the total revenue generated by the sale of electronic devices



import java.util.ArrayList;
import java.util.Scanner;

class ElectronicDevice {
    String modelNumber;
    String brandName;
    double price;

    public ElectronicDevice(String modelNumber, String brandName, double price) {
        this.modelNumber = modelNumber;
        this.brandName = brandName;
        this.price = price;
    }

    public String toString() {
        return "Model Number: " + modelNumber + ", Brand Name: " + brandName + ", Price: " + price;
    }
}

public class Q7_Electronic_device {
    public static void main(String[] args) {
        ArrayList<ElectronicDevice> inventory = new ArrayList<ElectronicDevice>();
        Scanner scanner = new Scanner(System.in);

        while (true) {
            System.out.println("Enter 1 to add a new electronic device to the inventory");
            System.out.println("Enter 2 to remove an electronic device from the inventory");
            System.out.println("Enter 3 to search for an electronic device by model number or brand name");
            System.out.println("Enter 4 to display the inventory list with all the details of each electronic device");
            System.out.println("Enter 5 to calculate the total revenue generated by the sale of electronic devices");
            System.out.println("Enter 6 to exit");

            int choice = scanner.nextInt();

            if (choice == 1) {
                System.out.println("Enter the model number:");
                String modelNumber = scanner.next();
                System.out.println("Enter the brand name:");
                String brandName = scanner.next();
                System.out.println("Enter the price:");
                double price = scanner.nextDouble();
                ElectronicDevice device = new ElectronicDevice(modelNumber, brandName, price);
                inventory.add(device);
                System.out.println("Device added to the inventory.");
            } else if (choice == 2) {
                System.out.println("Enter the model number of the device you want to remove:");
                String modelNumber = scanner.next();
                for (int i = 0; i < inventory.size(); i++) {
                    if (inventory.get(i).modelNumber.equals(modelNumber)) {
                        inventory.remove(i);
                        System.out.println("Device removed from the inventory.");
                        break;
                    }
                }
            } else if (choice == 3) {
                System.out.println("Enter the model number or brand name of the device you want to search:");
                String keyword = scanner.next();
                boolean found = false;
                for (int i = 0; i < inventory.size(); i++) {
                    if (inventory.get(i).modelNumber.equals(keyword) || inventory.get(i).brandName.equals(keyword)) {
                        System.out.println(inventory.get(i).toString());
                        found = true;
                    }
                }
                if (!found) {
                    System.out.println("Device not found in the inventory.");
                }
            } else if (choice == 4) {
                System.out.println("Inventory List:");
                for (int i = 0; i < inventory.size(); i++) {
                    System.out.println(inventory.get(i).toString());
                }
            } else if (choice == 5) {
                double revenue = 0.0;
                for (int i = 0; i < inventory.size(); i++) {
                    revenue += inventory.get(i).price;
                }
                System.out.println("Total revenue generated by the sale of electronic devices: " + revenue);
            } else if (choice == 6) {
                System.out.println("Exiting...");
                break;
            } else {
                System.out.println("Invalid choice. Please try again.");
            }
        }
        scanner.close();
    }
}